### ISSUE TITLE
Make directories list configurable

### ISSUE THREAD

**Issue by brpaz** [tinytacoteam/zazu-file-finder#11]
I have an External Hard drive mounted on /media/DATA. I would like to make it searchable from zazu.
It would be great if we can extend the default directories list.

**Comment by kozlown** [comment]
I agree, I don't want the /opt but I want the /bin with my Ubuntu for example ..

**Comment by blainesch** [comment]
Great idea!

**Comment by JeroenBoersma** [comment]
This is fixed in the latest release...

You can define your directories in your `zazurc.json`

See the [readme.md](https://github.com/tinytacoteam/zazu-file-finder/blob/master/readme.md) howto do this.
