### ISSUE TITLE
can zazu find files on networked drives?

### ISSUE THREAD

**Issue by stanley11235** [tinytacoteam/zazu-file-finder#14]
I don't store anything locally; it's all on networked drives or dropbox...so the file finder seems to be useless for me. Help? Would love an alternative to launchy (which is slow and buggy.)

**Comment by cecoates** [comment]
If you're using Linux you could try mounting the NAS as a drive, and then editing the directories.js to add that drive/folder. 

But you may run into the ownership issues mentioned here: https://github.com/tinytacoteam/zazu-file-finder/issues/12

**Comment by blainesch** [comment]
No, but I'd love for this to be configurable. If anybody wants to add this feature, feel free to make a pr! :D

**Comment by JeroenBoersma** [comment]
You can define your own directories now in `zazurc.json`
So, just add your directories.

Update your plugins for this.
See the [readme.md](https://github.com/tinytacoteam/zazu-file-finder/blob/master/readme.md)
