### ISSUE TITLE
Add Option to Search Only On 'Find' Keyword

### ISSUE THREAD

**Issue by Koolstr** [tinytacoteam/zazu-file-finder#19]
I've noticed that this plugin slows down Zazu immensely, but that may be simply due to my library indexing size (in which case, I'd recommend optimizing your indexing and retrieval to be as immediate as the incredibly fast 'Everything' search tool:  [https://www.voidtools.com/](https://www.voidtools.com)).

I know that when I have this plugin uninstalled, Zazu is as speedy as it should be. So this plugin is also responsible for the laggy search box text updates (before the results are displayed).

I would like for you to include an option that would cause Zazu to only 'activate' your plugin and display results, when the search on Zazu is begun with the keyword 'Find'. This should resolve the substantial latency issue, by making it so that I only have to deal with the sluggishness when I am using Zazu to search for files. ;)

Obviously, the more ideal but much more difficult solution would be to optimize its search and indexing algorithms. Until this is done, I'm going to keep this plugin uninstalled.

**Comment by blainesch** [comment]
That should already be the case.

We have [3 inputs](https://github.com/tinytacoteam/zazu-file-finder/blob/master/zazu.json#L14). The first is the app finder, which searches a local cache only. The second and third are part of the file manager and require a prefix (find/open) to start using them.

Also, we should be doing all the actual searching in a forked process, so it shouldn't directly effect you unless it was slowing down the entire system, not just zazu.

Do you mind posting the specs to your box? Also, the directory sizes of the [directories it's searching for/indexing](https://github.com/tinytacoteam/zazu-file-finder/blob/master/directories.js). Maybe I can try and get a better idea of what the problem is then.

**Comment by Koolstr** [comment]
Sure, but how comprehensive specs are you looking for? Models or raw power levels? And how/where can I see which directories this plugin is indexing? Normally I would be able to white/blacklist directories but I can't figure it out in yours.

**Comment by blainesch** [comment]
Just some basic specs processor/memory kinda of things.

The default directories are listed in here, under your os:

https://github.com/tinytacoteam/zazu-file-finder/blob/master/directories.js

Directories can be overwritten falling the file finder docs:

https://github.com/tinytacoteam/zazu-file-finder#installing

**Comment by cecoates** [comment]
Just out of curiosity, how large is your applications.json? I found that when mine was 500k+ (with lots and lots of items indexed) Zazu would slow down a lot with the first few characters you typed.

I ended up going with this:

   {
	"name": "tinytacoteam/zazu-file-finder",
	"variables": {
	"append": false,
	"directories": {
		"filePath": [
		"~/Documents",
                "~/Music"
			],
		"appPath": [
		"/usr/bin",
                "~/bin"
			]
			}
		}
    }

To exclude opt (Wine/Crossover had a lot of files that was slowing it down), and I removed the executable permission from a lot of random game files like maps in my ~/bin. Now it's pretty zippy, and it only seems to lag on characters that match a directory with a lot of files in it, like usr.

https://github.com/tinytacoteam/zazu/issues/125#issuecomment-273370257

![screen shot 2017-01-20 at 19 48 1 29](https://cloud.githubusercontent.com/assets/10121835/22171161/b16fa524-df4d-11e6-8bbf-62f657a111cf.jpg)

**Comment by Koolstr** [comment]
I'm running Windows 10, so your advice is less helpful than it could be. My applications.json was also over 500KB, and I excluded the filePath to only index one folder from my computer. Nonetheless, search is still slow and laggy. Perhaps you are right that the app.json is slowing it down. But what can I do to get it to exclude all files except fro .exe's in the listed directories?

My specs are as follows: Intel i7 4720HQ CPU 2.6GHz, 8GB RAM, 250GB SSD, HP OMEN, Windows 10 64-bit.

**Comment by blainesch** [comment]
If you don't want it to index your applications you can organize your directories like this:

~~~ json
{
  "plugins": [
    {
      "name": "tinytacoteam/zazu-file-finder",
      "variables": {
        "append": false,
        "directories": {
          "appPath": [],
        }
      }
    }
  ]
}
~~~

The important parts is that we are setting `append` to `false` so it overwrites the `appPath` which we set to an empty array. So now it'll only find things on `find` and `open` without indexing your computer for applications.
