### ISSUE TITLE
Index .exe file extensions on Windows

### ISSUE THREAD

**Issue by ppoetsma** [tinytacoteam/zazu-file-finder#37]
Hi,

On Windows only .lnk file extensions are indexed for appPath. As there can be more than just that I would like to index .exe files too. I work a lot with portable apps and those are not officially registered in Windows as applications.

And why not make it configurable in zazurc.json? See example below.

    {
      "name": "tinytacoteam/zazu-file-finder",
      "variables": {
        "append": true,
        "directories": {
          "filePath": [
            "~/Documents", "~/Nextcloud"
          ],
          "appPathExtended": [
            { "appPath": "~/PORTABLEAPPS", "appExt": "lnk;exe" }
          ]
        }
      }
    },

**Comment by blainesch** [comment]
Adding this sounds great. Thanks for the suggestion. It might be more complex since "extension" is only one way we detect if it's an application, for example on linux we index "executable" files. This might be a reason to start breaking the os's into their own plugin.
