### ISSUE TITLE
Can't find folders...

### ISSUE THREAD

**Issue by djalmaaraujo** [tinytacoteam/zazu-file-finder#40]
### Expected Behavior
I should be able to type "Screens..." and Zazu returns me "Screenshots" folder in ~/Dropbox/Screenshots

### Actual Behavior
nothing. Suggest to find on google

### Steps to reproduce the behavior
- open zazu
- type the name of one folder you use a lot

### Versions

* Zazu: latest
* OS: macos high sierra
* GIT:

Please, include a link to gist of most applicable `~/.zazu/log/` file.

**Comment by blainesch** [comment]
Great suggestion!

The code, for mac, would live somewhere around here:

https://github.com/tinytacoteam/zazu-file-finder/blob/master/adapters/osx-mdfind/index.js#L16

It's using `mdfind` and has the ability to search for a `type` and there is a type for folder that just needs to be included.

You can see this being done with the app query:

https://github.com/tinytacoteam/zazu-file-finder/blob/master/adapters/osx-mdfind/index.js#L5

**Comment by djalmaaraujo** [comment]
@blainesch How do I test the local plugin in zazu? I can make this contribution.

**Comment by djalmaaraujo** [comment]
Closing.. it actually already find folders, but the files has priority on the results, that's why I didn't see bfore.

**Comment by djalmaaraujo** [comment]
<img width="641" alt="screenshot 2017-10-17 13 34 07" src="https://user-images.githubusercontent.com/3402/31665173-e88483d8-b33f-11e7-91b4-fba23ba8000f.png">
<img width="681" alt="screenshot 2017-10-17 13 34 21" src="https://user-images.githubusercontent.com/3402/31665174-e8a74562-b33f-11e7-8c4b-542ebf9aa02b.png">
