### ISSUE TITLE
Resolution:  If you have a "Uncaught Exception" after updated to version 1.1.0 on macOS

### ISSUE THREAD

**Issue by acbetter** [tinytacoteam/zazu-file-finder#44]
> A JavaScript error occurred in the main process
> 
> The "oldPath" argument must be one of type string, Buffer, or URL.

![image](https://user-images.githubusercontent.com/13360124/61212653-7fc17180-a735-11e9-88a6-4d1c92170bf6.png)

If you have these issues after [Result items don't match what i type on macOS #351 fix](https://github.com/tinytacoteam/zazu/issues/351), **Here's Resolution**

1. delete `zazu-file-finder` directory in `~/.zazu/plugins/tinytacoteam/zazu-file-finder`
2. click `Zazu` and choose `Update Plugins`
3. click `Zazu` and choose `Toggle Zazu`
4. after `Zazu` load finished,`Toggle Zazu` and type something
5. **quit  `Zazu`**
6. open `Zazu`, `Toggle Zazu` and type something

---

Step 5 & 6 for clean `Zazu` app icon cache for macOS. If it doesn't work, repeat Step 5 & 6 until it works properly.

**Comment by linonetwo** [comment]
I found it hard to catch all error in electron v5.

So it is caused by outdated cache? Glad you found the way to solve and thank you for posted it here.

**Comment by linonetwo** [comment]
So it actually won't happen again?

**Comment by acbetter** [comment]
> So it actually won't happen again?

Yes, after cleaned the outdated cache, it won't happen again.
